### PR TITLE
handle "Unauthorized" exceptions in echobot

### PR DESCRIPTION
**Pull request by rahiel**
This will handle "Unauthorized" exceptions in the echobot example, helping future users from getting issues like #103.

Maybe we should mention that the recommended way to start is to base bots on the echobot code, because it handles many exceptions now.

### CODE REVIEW

**Comment by jh0ker** [comment]
Nice, thank you :)

**Comment by jh0ker** [comment]
@veralfre Please send me the link of your github/whatever project page and I''ll review it :)

**Comment by veralfre** [comment]
RIght now I can send you a zip file because I haven't uploaded it yet anywhere :+1:

**Comment by jh0ker** [comment]
Okay, but generally, I'd rather link to a project page than include the code in the repo. It's easier for you to push changes to the code and it makes it more clear that it's your project. Message me on telegram @jh0ker

**Comment by rahiel** [comment]
@jh0ker, you didn't merge the pull request, only closed it. Was that on purpose?

**Comment by jh0ker** [comment]
oops

**Comment by veralfre** [comment]
Check my account I pushed source files few seconds ago :+1:

**Pull request merged**
